[package]
name = "huffman"
version = "0.1.0"
edition = "2024"

[dependencies]
owo-colors = "4.2.0"
ternary = { path = "../ternary_machine/ternary" , features = ["const_size"]}
terscii = { path = "../ternary_machine/terscii" }
